PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "ai_scan_beosztas_form" ("beosztas_id" text, "form_name" text, "platform" text);
INSERT INTO ai_scan_beosztas_form VALUES('2','ai_scan_setting','web');
INSERT INTO ai_scan_beosztas_form VALUES('2','ai_scan_coordinator_dashboard','web');
INSERT INTO ai_scan_beosztas_form VALUES('2','ai_scan_agent_dashboard','web');
INSERT INTO ai_scan_beosztas_form VALUES('2','ai_scan_qa_job','web');
INSERT INTO ai_scan_beosztas_form VALUES('1','ai_scan_agent_dashboard','web');
INSERT INTO ai_scan_beosztas_form VALUES('1','ai_scan_qa_job','web');
COMMIT;